### ISSUE TITLE
Alex-related errors building with newer stackage snapshot

### ISSUE THREAD

**Issue by RichardWarfield** [bjpop/language-python#50]
I get the following errors when trying to build with Stackage snapshot 13.29 (GHC 8.6.5).  I'm not familiar with Alex so am not sure where these identifiers should be defined.

```haskell
/home/richard/workspace/third-party/language-python/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/Language/Python/Version2/Parser/Lexer.hs:45:14: error:
    Not in scope: type constructor or class ‘AlexAddr’
   |
45 | alex_base :: AlexAddr
   |              ^^^^^^^^

/home/richard/workspace/third-party/language-python/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/Language/Python/Version2/Parser/Lexer.hs:49:15: error:
    Not in scope: type constructor or class ‘AlexAddr’
   |
49 | alex_table :: AlexAddr
   |               ^^^^^^^^

/home/richard/workspace/third-party/language-python/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/Language/Python/Version2/Parser/Lexer.hs:53:15: error:
    Not in scope: type constructor or class ‘AlexAddr’
   |
53 | alex_check :: AlexAddr
   |               ^^^^^^^^

/home/richard/workspace/third-party/language-python/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/Language/Python/Version2/Parser/Lexer.hs:57:15: error:
    Not in scope: type constructor or class ‘AlexAddr’
   |
57 | alex_deflt :: AlexAddr
   |               ^^^^^^^^

/home/richard/workspace/third-party/language-python/src/Language/Python/Version2/Parser/Lexer.x:226:5: error:
    Not in scope: data constructor ‘AlexEOF’
    |
226 |     AlexEOF -> do
    |     ^^^^^^^

/home/richard/workspace/third-party/language-python/src/Language/Python/Version2/Parser/Lexer.x:244:5: error:
    Not in scope: data constructor ‘AlexError’
    |
244 |     AlexError _ -> lexicalError
    |     ^^^^^^^^^

/home/richard/workspace/third-party/language-python/src/Language/Python/Version2/Parser/Lexer.x:245:5: error:
    Not in scope: data constructor ‘AlexSkip’
    |
245 |     AlexSkip (nextLocation, _bytes, rest) len -> do
    |     ^^^^^^^^

/home/richard/workspace/third-party/language-python/src/Language/Python/Version2/Parser/Lexer.x:249:5: error:
    Not in scope: data constructor ‘AlexToken’
    Perhaps you meant variable ‘lexToken’ (line 221)
    |
249 |     AlexToken (nextLocation, _bytes, rest) len action -> do
    |     ^^^^^^^^^
```

`stack exec -- alex --version` gives `Alex version 3.2.4, (c) 2003 Chris Dornan and Simon Marlow`
